// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa8JjQEOM4ZD3UkNYh0LYoO00QhhOHMX8',
    appId: '1:325657605303:web:654e5ddfa68efd88d9c932',
    messagingSenderId: '325657605303',
    projectId: 'city-helper-system-8de0d',
    authDomain: 'city-helper-system-8de0d.firebaseapp.com',
    storageBucket: 'city-helper-system-8de0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQSLSsXI8MZpsfUUA6kl5VNss9EV1yl0Q',
    appId: '1:325657605303:android:f9da00f7362ca7b4d9c932',
    messagingSenderId: '325657605303',
    projectId: 'city-helper-system-8de0d',
    storageBucket: 'city-helper-system-8de0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmQirQYlwPfMj77laXMWaNc5NOU4TRMzg',
    appId: '1:325657605303:ios:82a89f777a52b8e2d9c932',
    messagingSenderId: '325657605303',
    projectId: 'city-helper-system-8de0d',
    storageBucket: 'city-helper-system-8de0d.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

}