import 'package:app/src/core/models/my_data_types.dart';
import 'package:app/src/core/models/opening_hours.dart';
import 'package:app/src/features/home_detail/domain/entity_detail.dart';
import 'package:app/src/features/home_detail/domain/rating_breakdown.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class FoodDetail extends EntityDetail {
  final GenderPreference genderPref;
  FoodDetail({
    required super.id,
    required super.categoryId,
    required super.subCategoryId,
    required super.coverImageUrl,
    required super.name,
    required super.cityName,
    required super.sectorName,
    required super.latLng,
    required super.avgRating,
    required super.totalReviews,
    required super.ratingBreakdown,
    required super.isPopular,
    required super.openingHours,
    required super.entityStatus,
    required super.createdAt,
    required super.ownerId,
    required super.description,
    required super.imageUrls,
    required super.streetAddress,
    required super.phoneNumber,
    required super.messagingNumber,
    required super.updatedAt,
    super.email,
    super.facebookUrl,
    super.instagramUrl,
    super.websiteUrl,
    required this.genderPref,
  });

  FoodDetail copyWith({
    EntityId? id,
    CategoryId? categoryId,
    SubCategoryId? subCategoryId,
    String? coverImageUrl,
    String? name,
    String? cityName,
    String? sectorName,
    LatLng? latLng,
    double? avgRating,
    int? totalReviews,
    List<RatingBreakdown>? ratingBreakdown,
    bool? isPopular,
    List<OpeningHours>? openingHours,
    EntityStatus? entityStatus,
    DateTime? createdAt,
    UserId? ownerId,
    String? description,
    List<String>? imageUrls,
    String? streetAddress,
    String? phoneNumber,
    String? messagingNumber,
    String? websiteUrl,
    String? instagramUrl,
    String? facebookUrl,
    String? email,
    DateTime? updatedAt,
    GenderPreference? genderPref,
  }) {
    return FoodDetail(
      id: id ?? this.id,
      categoryId: categoryId ?? this.categoryId,
      subCategoryId: subCategoryId ?? this.subCategoryId,
      coverImageUrl: coverImageUrl ?? this.coverImageUrl,
      name: name ?? this.name,
      cityName: cityName ?? this.cityName,
      sectorName: sectorName ?? this.sectorName,
      latLng: latLng ?? this.latLng,
      avgRating: avgRating ?? this.avgRating,
      totalReviews: totalReviews ?? this.totalReviews,
      ratingBreakdown: ratingBreakdown ?? this.ratingBreakdown,
      isPopular: isPopular ?? this.isPopular,
      openingHours: openingHours ?? this.openingHours,
      entityStatus: entityStatus ?? this.entityStatus,
      createdAt: createdAt ?? this.createdAt,
      ownerId: ownerId ?? this.ownerId,
      description: description ?? this.description,
      imageUrls: imageUrls ?? this.imageUrls,
      streetAddress: streetAddress ?? this.streetAddress,
      phoneNumber: phoneNumber ?? this.phoneNumber,
      messagingNumber: messagingNumber ?? this.messagingNumber,
      websiteUrl: websiteUrl ?? this.websiteUrl,
      instagramUrl: instagramUrl ?? this.instagramUrl,
      facebookUrl: facebookUrl ?? this.facebookUrl,
      email: email ?? this.email,
      updatedAt: updatedAt ?? this.updatedAt,
      genderPref: genderPref ?? this.genderPref,
    );
  }
}
