import 'package:app/src/core/models/my_data_types.dart';
import 'package:app/src/core/constants/default_opening_hours.dart';
import 'package:app/src/features/home/domain/entity.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:app/src/features/home/domain/pricing.dart';

final List<Residence> testResidences = [
  Residence(
    id: 'res_001',
    categoryId: 1,
    subCategoryId: 1,
    coverImageUrl: 'assets/images/residence/1.png',
    name: 'Cozy Apartment in Mirpur',
    cityName: 'Mirpur',
    sectorName: 'F1',
    latLng: LatLng(33.1840, 73.5186),
    avgRating: 4.5,
    totalReviews: 120,
    isPopular: true,
    openingHours: defaultOpeningHours,
    pricing: Pricing(
      cost: 25000,
      period: PricingPeriod.month,
      unit: PricingUnit.room,
    ),
    genderPref: GenderPreference.familyFriendly,
    isFurnished: true,
    status: ApprovalStatus.approved,
    isRoomAvailable: true, // Added
    updatedAt: DateTime.now(),
  ),
  Residence(
    id: 'res_002',
    categoryId: 1,
    subCategoryId: 2,
    coverImageUrl: 'assets/images/residence/2.png',
    name: 'Luxury Flat with Scenic View',
    cityName: 'Mirpur',
    sectorName: 'C4',
    latLng: LatLng(33.1885, 73.5112),
    avgRating: 4.8,
    totalReviews: 95,
    isPopular: true,
    openingHours: null, // No specific office hours
    pricing: Pricing(cost: 40000),
    genderPref: GenderPreference.maleOnly,
    isFurnished: true,
    status: ApprovalStatus.approved,
    isRoomAvailable: false, // Added
    updatedAt: DateTime.now(),
  ),
  Residence(
    id: 'res_003',
    categoryId: 2,
    subCategoryId: 1,
    coverImageUrl: 'assets/images/residence/3.png',
    name: 'Affordable Hostel for Students',
    cityName: 'Mirpur',
    sectorName: 'D2',
    latLng: LatLng(33.1862, 73.5214),
    avgRating: 3.9,
    totalReviews: 60,
    isPopular: false,
    openingHours: defaultOpeningHours,
    pricing: Pricing(cost: 8000),
    genderPref: GenderPreference.maleOnly,
    isFurnished: false,
    status: ApprovalStatus.approved,
    isRoomAvailable: true, // Added
    updatedAt: DateTime.now(),
  ),
  Residence(
    id: 'res_004',
    categoryId: 1,
    subCategoryId: 3,
    coverImageUrl: 'assets/images/residence/4.png',
    name: 'Shared Apartment with Roommates',
    cityName: 'Mirpur',
    sectorName: 'B1',
    latLng: LatLng(33.1831, 73.5179),
    avgRating: 4.2,
    totalReviews: 85,
    isPopular: false,
    openingHours: null, // No specific office hours
    pricing: Pricing(cost: 15000),
    genderPref: GenderPreference.femaleOnly,
    isFurnished: true,
    status: ApprovalStatus.approved,
    isRoomAvailable: false, // Added
    updatedAt: DateTime.now(),
  ),
  Residence(
    id: 'res_005',
    categoryId: 2,
    subCategoryId: 2,
    coverImageUrl: 'assets/images/residence/5.png',
    name: 'Girls Hostel with Facilities',
    cityName: 'Mirpur',
    sectorName: 'E3',
    latLng: LatLng(33.1893, 73.5167),
    avgRating: 4.7,
    totalReviews: 100,
    isPopular: false,
    openingHours: defaultOpeningHours,
    pricing: Pricing(cost: 12000),
    genderPref: GenderPreference.femaleOnly,
    isFurnished: true,
    status: ApprovalStatus.approved,
    isRoomAvailable: true, // Added
    updatedAt: DateTime.now(),
  ),
  Residence(
    id: 'res_006',
    categoryId: 1,
    subCategoryId: 1,
    coverImageUrl: 'assets/images/residence/6.png',
    name: 'Penthouse Living',
    cityName: 'Mirpur',
    sectorName: 'A2',
    latLng: LatLng(33.1857, 73.5144),
    avgRating: 4.9,
    totalReviews: 150,
    isPopular: true,
    openingHours: null, // No specific office hours
    pricing: Pricing(cost: 60000),
    genderPref: GenderPreference.familyFriendly,
    isFurnished: true,
    status: ApprovalStatus.approved,
    isRoomAvailable: false, // Added
    updatedAt: DateTime.now(),
  ),
  Residence(
    id: 'res_007',
    categoryId: 2,
    subCategoryId: 3,
    coverImageUrl: 'assets/images/residence/7.png',
    name: 'Budget Hostel with Basic Needs',
    cityName: 'Mirpur',
    sectorName: 'F3',
    latLng: LatLng(33.1829, 73.5120),
    avgRating: 3.5,
    totalReviews: 45,
    isPopular: false,
    openingHours: defaultOpeningHours,
    pricing: Pricing(cost: 7000),
    genderPref: GenderPreference.maleOnly,
    isFurnished: false,
    status: ApprovalStatus.approved,
    isRoomAvailable: true, // Added
    updatedAt: DateTime.now(),
  ),
  Residence(
    id: 'res_008',
    categoryId: 1,
    subCategoryId: 2,
    coverImageUrl: 'assets/images/residence/8.png',
    name: 'Stylish Studio Apartment',
    cityName: 'Mirpur',
    sectorName: 'C1',
    latLng: LatLng(33.1875, 73.5191),
    avgRating: 4.3,
    totalReviews: 70,
    isPopular: true,
    openingHours: null, // No specific office hours
    pricing: Pricing(cost: 28000),
    genderPref: GenderPreference.familyFriendly,
    isFurnished: true,
    status: ApprovalStatus.approved,
    isRoomAvailable: false, // Added
    updatedAt: DateTime.now(),
  ),
  Residence(
    id: 'res_009',
    categoryId: 2,
    subCategoryId: 1,
    coverImageUrl: 'assets/images/residence/9.png',
    name: 'Comfortable Hostel for Girls',
    cityName: 'Mirpur',
    sectorName: 'G2',
    latLng: LatLng(33.1869, 73.5155),
    avgRating: 4.4,
    totalReviews: 88,
    isPopular: true,
    openingHours: defaultOpeningHours,
    pricing: Pricing(cost: 11000),
    genderPref: GenderPreference.femaleOnly,
    isFurnished: true,
    status: ApprovalStatus.approved,
    isRoomAvailable: true, // Added
    updatedAt: DateTime.now(),
  ),
  Residence(
    id: 'res_010',
    categoryId: 1,
    subCategoryId: 3,
    coverImageUrl: 'assets/images/residence/10.png',
    name: 'Family Apartment with Parking',
    cityName: 'Mirpur',
    sectorName: 'H1',
    latLng: LatLng(33.1838, 73.5105),
    avgRating: 4.6,
    totalReviews: 110,
    isPopular: true,
    openingHours: null, // No specific office hours
    pricing: Pricing(cost: 35000),
    genderPref: GenderPreference.familyFriendly,
    isFurnished: true,
    status: ApprovalStatus.approved,
    isRoomAvailable: false, // Added
    updatedAt: DateTime.now(),
  ),
];
