import 'package:app/src/features/home/domain/carousel_ad.dart';

final List<CarouselAd> testCarouselAds = [
  // Ads for Residences (Category 1, Subcategory 1)
  CarouselAd(
    categoryId: 1,
    subCategoryId: 1,
    id: '1',
    imageUrl: "assets/carousel_ads/image_1.jpg",
    targetUrl: "https://example.com/luxury-rooms",
    validFrom: DateTime(2024, 1, 1),
    validUntil: DateTime(2024, 12, 31),
  ),
  CarouselAd(
    categoryId: 1,
    subCategoryId: 1,
    id: '2',
    imageUrl: "assets/carousel_ads/image_1.jpg",
    targetUrl: "https://example.com/affordable-flats",
    validFrom: DateTime(2024, 2, 1),
    validUntil: DateTime(2024, 12, 31),
  ),
  CarouselAd(
    categoryId: 1,
    subCategoryId: 1,
    id: '3',
    imageUrl: "assets/carousel_ads/image_1.jpg",
    targetUrl: "https://example.com/hostel-rooms",
    validFrom: DateTime(2024, 3, 1),
    validUntil: DateTime(2024, 12, 31),
  ),
  CarouselAd(
    categoryId: 1,
    subCategoryId: 1,
    id: '4',
    imageUrl: "assets/carousel_ads/image_1.jpg",
    targetUrl: "https://example.com/furnished-rooms",
    validFrom: DateTime(2024, 4, 1),
    validUntil: DateTime(2024, 12, 31),
  ),
  CarouselAd(
    categoryId: 1,
    subCategoryId: 1,
    id: '5',
    imageUrl: "assets/carousel_ads/image_1.jpg",
    targetUrl: "https://example.com/student-hostels",
    validFrom: DateTime(2024, 5, 1),
    validUntil: DateTime(2024, 12, 31),
  ),

  // Ads for Food (Category 2, Subcategory 2)
  CarouselAd(
    categoryId: 2,
    subCategoryId: 2,
    id: '6',
    imageUrl: "assets/carousel_ads/image_1.jpg",
    targetUrl: "https://example.com/pizza-deals",
    validFrom: DateTime(2024, 1, 1),
    validUntil: DateTime(2024, 12, 31),
  ),
  CarouselAd(
    categoryId: 2,
    subCategoryId: 2,
    id: '7',
    imageUrl: "assets/carousel_ads/image_1.jpg",
    targetUrl: "https://example.com/cafe-offers",
    validFrom: DateTime(2024, 2, 1),
    validUntil: DateTime(2024, 12, 31),
  ),
  CarouselAd(
    categoryId: 2,
    subCategoryId: 2,
    id: '8',
    imageUrl: "assets/carousel_ads/image_1.jpg",
    targetUrl: "https://example.com/takeaway-deals",
    validFrom: DateTime(2024, 3, 1),
    validUntil: DateTime(2024, 12, 31),
  ),
  CarouselAd(
    categoryId: 2,
    subCategoryId: 2,
    id: '9',
    imageUrl: "assets/carousel_ads/image_1.jpg",
    targetUrl: "https://example.com/fast-food",
    validFrom: DateTime(2024, 4, 1),
    validUntil: DateTime(2024, 12, 31),
  ),
  CarouselAd(
    categoryId: 2,
    subCategoryId: 2,
    id: '10',
    imageUrl: "assets/carousel_ads/image_1.jpg",
    targetUrl: "https://example.com/healthy-food",
    validFrom: DateTime(2024, 5, 1),
    validUntil: DateTime(2024, 12, 31),
  ),
];
