import 'package:app/src/core/models/my_data_types.dart';
import 'package:app/src/core/models/opening_hours.dart';
import 'package:app/src/features/home/domain/categories/food.dart';
import 'package:app/src/features/home_detail/domain/rating_breakdown.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

final List<Food> testFoods = [
  Food(
    id: '1',
    categoryId: 2,
    subCategoryId: 6,
    coverImageUrl: 'assets/images/food/1.png',
    name: 'Tasty Bites',
    cityName: 'City A',
    sectorName: 'A1',
    latLng: LatLng(34.0522, -118.2437),
    avgRating: 4.5,
    totalReviews: 120,
    isPopular: true,
    openingHours: _defaultOpeningHours,
    entityStatus: EntityStatus.defaultStatus,
    genderPref: GenderPreference.familyFriendly,
    createdAt: DateTime.now(),
    ratingBreakdown: [
      RatingBreakdown(starRating: 5, ratingCount: 80),
      RatingBreakdown(starRating: 4, ratingCount: 25),
      RatingBreakdown(starRating: 3, ratingCount: 10),
      RatingBreakdown(starRating: 2, ratingCount: 3),
      RatingBreakdown(starRating: 1, ratingCount: 2),
    ],
  ),
  Food(
    id: '2',
    categoryId: 2,
    subCategoryId: 6,
    coverImageUrl: 'assets/images/food/2.png',
    name: 'Spice Hub',
    cityName: 'City B',
    sectorName: 'A2',
    latLng: LatLng(40.7128, -74.0060),
    avgRating: 4.2,
    totalReviews: 98,
    isPopular: true,
    openingHours: _defaultOpeningHours,
    entityStatus: EntityStatus.defaultStatus,
    genderPref: GenderPreference.familyFriendly,
    createdAt: DateTime.now(),
    ratingBreakdown: [
      RatingBreakdown(starRating: 5, ratingCount: 60),
      RatingBreakdown(starRating: 4, ratingCount: 20),
      RatingBreakdown(starRating: 3, ratingCount: 10),
      RatingBreakdown(starRating: 2, ratingCount: 5),
      RatingBreakdown(starRating: 1, ratingCount: 3),
    ],
  ),
  Food(
    id: '3',
    categoryId: 2,
    subCategoryId: 7,
    coverImageUrl: 'assets/images/food/3.png',
    name: 'Coffee Corner',
    cityName: 'City C',
    sectorName: 'A3',
    latLng: LatLng(51.5074, -0.1278),
    avgRating: 4.7,
    totalReviews: 150,
    isPopular: true,
    openingHours: _defaultOpeningHours,
    entityStatus: EntityStatus.defaultStatus,
    genderPref: GenderPreference.familyFriendly,
    createdAt: DateTime.now(),
    ratingBreakdown: [
      RatingBreakdown(starRating: 5, ratingCount: 110),
      RatingBreakdown(starRating: 4, ratingCount: 25),
      RatingBreakdown(starRating: 3, ratingCount: 10),
      RatingBreakdown(starRating: 2, ratingCount: 3),
      RatingBreakdown(starRating: 1, ratingCount: 2),
    ],
  ),
  Food(
    id: '4',
    categoryId: 2,
    subCategoryId: 7,
    coverImageUrl: 'assets/images/food/4.png',
    name: 'Sweet Treats',
    cityName: 'City D',
    sectorName: 'A4',
    latLng: LatLng(48.8566, 2.3522),
    avgRating: 4.3,
    totalReviews: 80,
    isPopular: true,
    openingHours: _defaultOpeningHours,
    entityStatus: EntityStatus.defaultStatus,
    genderPref: GenderPreference.familyFriendly,
    createdAt: DateTime.now(),
    ratingBreakdown: [
      RatingBreakdown(starRating: 5, ratingCount: 50),
      RatingBreakdown(starRating: 4, ratingCount: 20),
      RatingBreakdown(starRating: 3, ratingCount: 5),
      RatingBreakdown(starRating: 2, ratingCount: 3),
      RatingBreakdown(starRating: 1, ratingCount: 2),
    ],
  ),
  Food(
    id: '5',
    categoryId: 2,
    subCategoryId: 8,
    coverImageUrl: 'assets/images/food/5.png',
    name: 'Burger King',
    cityName: 'City E',
    sectorName: 'A5',
    latLng: LatLng(35.6895, 139.6917),
    avgRating: 4.6,
    totalReviews: 200,
    isPopular: true,
    openingHours: _defaultOpeningHours,
    entityStatus: EntityStatus.defaultStatus,
    genderPref: GenderPreference.familyFriendly,
    createdAt: DateTime.now(),
    ratingBreakdown: [
      RatingBreakdown(starRating: 5, ratingCount: 150),
      RatingBreakdown(starRating: 4, ratingCount: 30),
      RatingBreakdown(starRating: 3, ratingCount: 10),
      RatingBreakdown(starRating: 2, ratingCount: 5),
      RatingBreakdown(starRating: 1, ratingCount: 5),
    ],
  ),
  Food(
    id: '6',
    categoryId: 2,
    subCategoryId: 8,
    coverImageUrl: 'assets/images/food/6.png',
    name: 'Homestyle Kitchen',
    cityName: 'City F',
    sectorName: 'A6',
    latLng: LatLng(37.7749, -122.4194),
    avgRating: 3.9,
    totalReviews: 75,
    isPopular: false,
    openingHours: _defaultOpeningHours,
    entityStatus: EntityStatus.defaultStatus,
    genderPref: GenderPreference.familyFriendly,
    createdAt: DateTime.now(),
    ratingBreakdown: [
      RatingBreakdown(starRating: 5, ratingCount: 35),
      RatingBreakdown(starRating: 4, ratingCount: 20),
      RatingBreakdown(starRating: 3, ratingCount: 10),
      RatingBreakdown(starRating: 2, ratingCount: 7),
      RatingBreakdown(starRating: 1, ratingCount: 3),
    ],
  ),
  Food(
    id: '7',
    categoryId: 2,
    subCategoryId: 9,
    coverImageUrl: 'assets/images/food/7.png',
    name: 'Tea Junction',
    cityName: 'City G',
    sectorName: 'A7',
    latLng: LatLng(55.7558, 37.6173),
    avgRating: 4.1,
    totalReviews: 65,
    isPopular: false,
    openingHours: _defaultOpeningHours,
    entityStatus: EntityStatus.defaultStatus,
    genderPref: GenderPreference.familyFriendly,
    createdAt: DateTime.now(),
    ratingBreakdown: [
      RatingBreakdown(starRating: 5, ratingCount: 40),
      RatingBreakdown(starRating: 4, ratingCount: 15),
      RatingBreakdown(starRating: 3, ratingCount: 5),
      RatingBreakdown(starRating: 2, ratingCount: 3),
      RatingBreakdown(starRating: 1, ratingCount: 2),
    ],
  ),
  Food(
    id: '8',
    categoryId: 2,
    subCategoryId: 9,
    coverImageUrl: 'assets/images/food/8.png',
    name: 'Golden Bakery',
    cityName: 'City H',
    sectorName: 'C8',
    latLng: LatLng(41.9028, 12.4964),
    avgRating: 4.0,
    totalReviews: 55,
    isPopular: false,
    openingHours: _defaultOpeningHours,
    entityStatus: EntityStatus.defaultStatus,
    genderPref: GenderPreference.familyFriendly,
    createdAt: DateTime.now(),
    ratingBreakdown: [
      RatingBreakdown(starRating: 5, ratingCount: 30),
      RatingBreakdown(starRating: 4, ratingCount: 15),
      RatingBreakdown(starRating: 3, ratingCount: 5),
      RatingBreakdown(starRating: 2, ratingCount: 3),
      RatingBreakdown(starRating: 1, ratingCount: 2),
    ],
  ),
];

final List<OpeningHours> _defaultOpeningHours = [
  OpeningHours(day: 'Monday', startTime: '9:00 AM', endTime: '9:00 PM'),
  OpeningHours(day: 'Tuesday', startTime: '9:00 AM', endTime: '9:00 PM'),
  OpeningHours(day: 'Wednesday', startTime: '9:00 AM', endTime: '9:00 PM'),
  OpeningHours(day: 'Thursday', startTime: '9:00 AM', endTime: '9:00 PM'),
  OpeningHours(day: 'Friday', startTime: '9:00 AM', endTime: '9:00 PM'),
  OpeningHours(day: 'Saturday', startTime: '9:00 AM', endTime: '9:00 PM'),
  OpeningHours(day: 'Sunday', startTime: '9:00 AM', endTime: '9:00 PM'),
];
