/// Base class for all all client-side errors that can be generated by the app
class AppException implements Exception {
  AppException(this.code, this.message);

  final String code;
  final String message;

  @override
  String toString() => message;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is AppException &&
        other.code == code &&
        other.message == message;
  }

  @override
  int get hashCode => Object.hash(code, message);
}

/// [InternetConnectionExceptions]
class NoInternetConnectionException extends AppException {
  NoInternetConnectionException()
      : super(
          'no-internet-connection',
          'Unable to connect to the internet. Please check your connection and try again.',
        );
}

/// [RequestCancelException]
class RequestCancelException extends AppException {
  RequestCancelException()
      : super(
          'request-cancelled',
          'The request was cancelled. Please try again.',
        );
}

/// [ConnectionTimeoutException]
class ConnectionTimeoutException extends AppException {
  ConnectionTimeoutException()
      : super(
          'connection-timeout',
          'The request timed out while trying to connect to the server. Please check your connection and try again.',
        );
}

/// [SendTimeoutException]
class SendTimeoutException extends AppException {
  SendTimeoutException()
      : super(
          'send-timeout',
          'The request took too long to send data to the server. Please try again.',
        );
}

/// [ReceiveTimeoutException]
class ReceiveTimeoutException extends AppException {
  ReceiveTimeoutException()
      : super(
          'receive-timeout',
          'The request took too long to receive data from the server. Please try again.',
        );
}

/// [ResponseException]
class ResponseException extends AppException {
  ResponseException(int? statusCode, String message)
      : super(
          'response-error',
          'Received an error response from the server. '
              'Status Code: $statusCode. Message: $message',
        );
}

/// [NetworkException]
class NetworkException extends AppException {
  NetworkException()
      : super(
          'network-error',
          'A network error occurred. Please check your internet connection and try again.',
        );
}

/// [TimedOutException]
class TimedOutException extends AppException {
  TimedOutException()
      : super(
          'time-out',
          'Request timed out. Please try again.',
        );
}

/// [UnknownException]
class UnknownException extends AppException {
  UnknownException() : super('unknown-error', 'An unknown error occurred.');
}
