name: Run Tests
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    # https://stackoverflow.com/a/63122434/436422
    defaults:
      run:
        working-directory: app
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - name: Create .env file with secrets
      run: |
        echo "OSM_TILE_URL=${{ secrets.OSM_TILE_URL }}" >> City Helper System/app/.env
        echo "USER_AGENT_PACKAGE_NAME=${{ secrets.USER_AGENT_PACKAGE_NAME }}" >> app/.env
    - run: flutter test
